name = "EquivalentFeatures"
uuid = "be892b62-896a-43c6-957c-84ed54769db5"
version = "0.1.1"


[deps]
SphericalHarmonicExpansions ="504afa71-bae7-47b4-8ec9-3851161806ac"
WignerSymbols               ="9f57e263-0b3d-5e2e-b1be-24f2bb48858b"
DataStructures              ="864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
MultivariatePolynomials     ="102ac46a-7ee4-5c85-9060-abc95bfdeaa3"
LinearAlgebra               ="37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SphericalHarmonics          ="c489a379-e885-57ff-9236-bd896d33c250" 

[compat] 
SphericalHarmonicExpansions ="0.1.4"
WignerSymbols               ="2.0.0"
DataStructures              ="0.19.3"
MultivariatePolynomials     ="0.4"
LinearAlgebra               = "1"
SphericalHarmonics          ="0.1.20"
